"""create user and organisation table migrations

Revision ID: 7d05c47555ca
Revises: 
Create Date: 2024-07-07 00:19:39.406920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d05c47555ca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('orgId', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('orgId')
    )
    op.create_index(op.f('ix_organisations_orgId'), 'organisations', ['orgId'], unique=False)
    op.create_table('users',
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(), nullable=False),
    sa.Column('lastName', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('userId'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_userId'), 'users', ['userId'], unique=False)
    op.create_table('user_organisation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.orgId'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('user_id', 'organisation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_organisation')
    op.drop_index(op.f('ix_users_userId'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_organisations_orgId'), table_name='organisations')
    op.drop_table('organisations')
    # ### end Alembic commands ###
